// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetStore.Models;

public partial class Order
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public string Status { get; set; }

    public int CustomerId { get; set; }

    public int EmployeeId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}